django/mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^recursion/', include('recursion.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django/mysite/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'

urlpatterns = [
    #ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results,name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

django/mysite/recursion/urls.py
from django.conf.urls import url

from . import views

app_name = 'recursion'

urlpatterns = [
 
    url(r'^$', views.index, name='index'),
 
    url(r'^(?P<fractal_id>[0-9]+)\/(?P<recursion_lvl>[0-9]+)$', views.detail, name='detail'),

    url(r'^(?P<fractal_id>[0-9]+)/vote/$', views.vote, name='vote'),

    url(r'^(?P<fractal_id>[0-9]+)/result/$', views.result, name='result'),
]

django/mysite/polls/models.py
from django.db import models

class Question(models.Model):    
    question_text = models.CharField(max_length=200)
    question_name = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):             
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):             
        return self.choice_text

django/mysite/recursion/models.py
from django.db import models
import os
from glob import glob

class Fractal(models.Model):
    fractal_name = models.CharField(max_length=200)
    angle = models.CharField(max_length=200)
    length = models.CharField(max_length=200)
    ratio = models.CharField(max_length=200)
    recursion_lvl = models.CharField(max_length=200)
    init_pos = models.CharField(max_length=200)
    init_heading = models.CharField(max_length=200)
    pen_color = models.CharField(max_length=200)
    fill_color = models.CharField(max_length=200)
    

    def __str__(self):             
        return self.fractal_name


    def save(self, *args, **kwargs):
        # print("todo: delete existing fractal images on fractal change")
        for f in glob("recursion/static/recursion/fractal_img_"+str(self.id)+"*.png"):
            os.remove(f)
        super(Fractal, self).save(*args, **kwargs)


class LSystem(models.Model):    
    fractal = models.ForeignKey(Fractal, on_delete=models.CASCADE)
    lsystem_symbol = models.CharField(max_length=200)
    lsystem_word = models.CharField(max_length=200)


    def __str__(self):          
        
        return (self.fractal.fractal_name + ": (" + self.lsystem_symbol + " --> " + self.lsystem_word + ")")


    def save(self, *args, **kwargs):
        # print("todo: delete existing fractal images on lsystem change")
        for f in glob("recursion/static/recursion/fractal_img_"+str(self.fractal.id)+"*.png"):
            os.remove(f)
        super(LSystem, self).save(*args, **kwargs)

django/mysite/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.http import Http404
# from django.core.urlresolvers import reverse

from .models import Question


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        # return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

django/mysite/recursion/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render
from recursion.Lindenmayer import *
import ast
import os
from random import random
from PIL import Image, ImageDraw
from .models import Fractal


def index(request):
    fractal_list = Fractal.objects.all()
    # create thumbnails
    for fractal in fractal_list:
        filename = "recursion/static/recursion/fractal_img_" + str(fractal.id) + "_thumbnail.png"

        createImage(fractal, filename, fractal.recursion_lvl, fractal.recursion_lvl)

        im = Image.open(filename)
        im.thumbnail((128, 128), Image.ANTIALIAS)
        im.save(filename)

    no_cache = str(int(round(random()*20000, 0))).zfill(5)

    template = loader.get_template('recursion/fractal_list.html')
    context = { "fractal_list" : fractal_list, "no_cache" : no_cache }
    return HttpResponse(template.render(context, request))


def detail(request, fractal_id, recursion_lvl):
    
    filename = "recursion/static/recursion/fractal_img_" + str(fractal_id) + "_" + str(recursion_lvl) + ".png"
    fractal = Fractal.objects.get(pk=fractal_id)
    max_lvl = 15
    
    createImage(fractal, filename, recursion_lvl, max_lvl)

    no_cache = str(int(round(random()*20000, 0))).zfill(5)

    template = loader.get_template('recursion/fractal_result.html')
    context = { "fractal" : fractal, "recursion_lvl" : recursion_lvl, "max_lvl" : max_lvl, "no_cache" : no_cache }
    return HttpResponse(template.render(context, request))

def result(request, fractal_id):
	return HttpResponse("result")

def vote(request, fractal_id):
    return HttpResponse("vote")


#helper 
def createImage(fractal, filename, recursion_lvl, max_lvl):

    if not os.path.isfile(filename):
        turty = TurtleImage((0,0), 0, filename)
        
        lsystems = fractal.lsystem_set.all()
        words = dict()
        for l in lsystems:
        	words[l.lsystem_symbol] = l.lsystem_word

        turty.seth(float(fractal.init_heading))
        pos = ast.literal_eval(fractal.init_pos)
        pos = [float(el) for el in pos]
        # print("pos: " + str(pos))
        turty.setpos(pos)

        recursion_lvl = int(recursion_lvl)
        

        # limit this or server will crash
        max_lvl = int(max_lvl)
        if recursion_lvl > max_lvl:
            recursion_lvl = max_lvl

        lm = Lindenmayer(turty, words, float(fractal.angle), 
        	float(fractal.length), float(fractal.ratio), int(recursion_lvl))

        msg = ""
        if lm is not None:
            # print("start lm")
            lm.start()
            msg = "lm finished"
        else:
            msg = "lm was none"
    else:
        print("requested image already there")

django/mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

django/mysite/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

django/mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

django/mysite/recursion/templates/recursion/fractal_list.html
<!-- Google fonts -->
<link href='http://fonts.googleapis.com/css?family=Vollkorn:400,700' rel='stylesheet' type='text/css'>


<!--style-->
<style type="text/css">
	/* = body
------------------------*/
body{
  background:#2E88C9;
}
.description{
  font-family: 'Vollkorn', serif;
  text-align:center;
  color:#ecf0f1;
  text-shadow:0 0.1em 0.2em #008c8d;
}
/* = Scroll body
------------------------*/
::-webkit-scrollbar{
  width:0.2em;
}
::-webkit-scrollbar-track{
  background-color:#bdc3c7;
}
::-webkit-scrollbar-thumb{
  background-color:#7f8c8d;
}
/* = table
------------------------*/
.box-table table{
  border-collapse:collapse;
  text-align:left;
  width:100%;
  margin:0;
  padding:0;
  background:#7f8c8d;
  animation: responsive 5s infinite ease-in-out;
}
.box-table{
  font:normal 12px/150% Arial, Helvetica, sans-serif;
  overflow:hidden;
  margin:0 auto;
  display:block;
  width:95%;
  padding:2.5%;
}
.box-table table thead th{
  background-color:#7f8c8d;
  /*color:#bdc3c7;*/
  text-align:center;
  padding: 0.75em;
  font-family: 'Vollkorn', serif;
  font-weight: bold;
  font-size: 1.5em;
  height: 1.5em;
  vertical-align: top;
  border-left:0.25em double #95a5a6;

}
.box-table table tbody td,
.box-table table tbody tr{
  font-family: 'Vollkorn', serif;
  font-size:1em;
  border:none;
  padding:1em;
}
.box-table table tbody tr:nth-child(odd){
  background:#ecf0f1;
  /*color:#95a5a6;*/
}
.box-table table tbody tr:nth-child(even){
  background:#bdc3c7;
  /*color:#7f8c8d;*/
}
.box-table table tbody tr a{
  text-decoration:none;
  /*color:#e67e22;*/
}
.box-table table tbody tr a:hover{
  /*color:#d35400;*/
}
.box-table .user-photo{
  /*background:#bdc3c7;*/
}
.box-table .user-tumb{
  width:6em;
  height:6em;
  padding:0;
  display:table-cell;
  text-align:center;
  margin:0 auto;
  -webkit-border-radius:100%;
  -moz-border-radius:100%;
  border-radius:100%;
}


/* = Responsive table
------------------------*/

/* http://elvery.net/demo/responsive-tables/  */
@media only screen and (max-width: 800px){
  .box-table table{
    width:100%;
    border-collapse:collapse;
    border-spacing:0;
  }
  .box-table th,
  .box-table td{
    margin:0;
    vertical-align:top;
  }
  .box-table th{
    text-align:left;
  }
  .box-table table{
    display:block;
    position:relative;
    width:100%;
  }
  .box-table thead{
    display:block;
    float:left;
  }
  .box-table tbody{
    display:block;
    width:auto;
    position:relative;
    overflow-x:auto;
    white-space:nowrap;
  }
  .box-table thead tr{
    display:block;
  }
  .box-table th{
    display:block;
    text-align:right;
  }
  .box-table tbody tr{
    display:inline-block;
    vertical-align:top;
  }
  .box-table td{
    display:block;
    min-height:1.25em;
    text-align:left;
  }
  .box-table th{
    border-bottom:0;
    border-left:0;
  }
  .box-table td{
    border-left:0;
    border-right:0;
    border-bottom:0;
  }
}
/* = Error
------------------------*/
.error_table {
  display: block;
  background: #E05E5E;
  color: #D1D1D1;
  font-family: 'Vollkorn', serif;
  text-align: center;
  font-size: 3em;
  width: 90%;
  padding: 5%;
}
/* = Loader
------------------------*/
.loading_table{
  background:#d35400;
  color:#ecf0f1;
  font-family: 'Vollkorn', serif;
  text-align: center;
  font-size: 1em;
  width: 0;
  display: block;
  overflow: hidden;
  height: 1em;
  padding:0.5em;
  animation: table_loader 10s infinite ease;
}
@keyframes table_loader{50%{width:100%}}
@-webkit-keyframes table_loader{50%{width:100%}}
@-moz-keyframes table_loader{50%{width:100%}}
@-ms-keyframes table_loader{50%{width:100%}}
@-o-keyframes table_loader{ 50%{width:100%}}
	
</style>

<h1 class="description">Simple Fractals</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<div class="box-table">
<table>
	<tr>
		<th></th>
		<th>Name</th>
		<th>Angle</th>
		<th>Length</th>
		<th>Ratio</th>
		<th>Recursion-Level</th>
		<th></th>
	</tr>
{% load static %}
{% for fractal in fractal_list %}
    <tr>
    	<td>
    		<a href="{% url 'recursion:detail' fractal.id fractal.recursion_lvl%}">
    		<img src="{% static "recursion/fractal_img_" %}{{fractal.id}}_thumbnail.png?no_cache={{no_cache}}" alt="fractal image"/>
    		</a>
    	</td>
    	<td>{{fractal.fractal_name}}</td>
    	<td>{{fractal.angle}}</td>
    	<td>{{fractal.length}}</td>
    	<td>{{fractal.ratio}}</td>
    	<td>{{fractal.recursion_lvl}}</td>
    	<!--<td><a href="{% url 'recursion:detail' fractal.id fractal.recursion_lvl%}">Go</a></td>-->
    </tr>
{% endfor %}
</table>
</div>
<a href="{% url 'admin:index' %}">Login</a>

django/mysite/recursion/templates/recursion/fractal_result.html
<h1>{{fractal.fractal_name}}</h1>
<a href="{% url 'recursion:index' %}">Back to List</a>
<br>
{% load static %}
Iterations: <input type="range"  min="0" max="{{max_lvl}}" value="{{recursion_lvl}}" style="width: 300px;" oninput="showValue(this.value)" onchange="reqNewIter(this.value)"/>
<span id="range">{{recursion_lvl}}</span>
<br>


<script type="text/javascript">
function showValue(newValue)
{
	document.getElementById("range").innerHTML=newValue;
}

function reqNewIter(newValue)
{
	destination = "http://" + window.location.host + "/recursion/" + "{{fractal.id}}/" + newValue;

	window.location = destination;
}
</script>
<img src="{% static "recursion/fractal_img_" %}{{fractal.id}}_{{recursion_lvl}}.png?no_cache={{no_cache}}" alt="fractal image"/>